### ISSUE TITLE
WDAC Tools do not work on Windows Server 2016

### ISSUE THREAD

**Issue by mfgjwaterman** [mattifestation/WDACTools#5] opened 2022-02-22 13:25 UTC
Hi,

I've been using the WDACTools for a couple of days now, but am running into issues when trying to use them on Windows Server. executing the "Get-WDACCodeIntegrityEvent" CMDlet, gives the error:

```
Exception calling "ToString" with "1" argument(s): "Value cannot be null.
Parameter name: value"
At C:\Users\Administrator\Desktop\WDACTools\WDACAuditing.psm1:605 char:26
+                 } else { $null }
+                          ~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException
```

I think it's partially because the eventid 3099 does not exist on Server 2016. Would it be possible to look into it, or is it not supported on Server 2016?

Thanks for any reply you can give.

**Comment by mattifestation** [comment] 2022-02-23 14:29
Hey @mfgjwaterman! Thanks for the report. Happy to help look into it. I can attempt to get a Server 2016 VM to test with if needed but before that, let me see what I might be able to suggest.

1. If you suspect that the issue is related to 3099 not being present, do you still get the error if you don't supply the `-SinceLastPolicyRefresh` switch?
2. Are you seeing CodeIntegrity 3076 or 3077 events that don't have a `SHA256FlatHash` field populated?
3. If you replace `$null` in line 605 with `''`, is the issue resolved?

Thanks!

**Comment by mfgjwaterman** [comment] 2022-02-23 14:45
Hi Hi,

Thanks for the reply. Here are my answers:

1. Yes, the same error is shown when I just running the cmdlet without any parameters.
2. Validated that all the SHA256FlatHash properties have been populated. (Used PowerShell)
3. Unfortunately not

Let me know if I can do anything to help! Have a VMWare lab available. 

PS: Not the correct place, but just wanted to let you know that your YT videos on the topic are a life saver!! Thanks for those.

**Comment by mattifestation** [comment] 2022-02-25 13:27
Thanks for your reply! I'm unable to reproduce the issue on my host but I will set up a Server 2016 VM and try to repro it and get this figured out. I may need a few days to respond though. Sorry for the delay and thank you for your patience!

So glad the YT videos were helpful for you!

**Comment by mfgjwaterman** [comment] 2022-02-25 13:35
No worries mate, I've figured out a work-around for now, but it would be wonderful if you got it to work. Hope you enjoy your weekend!

**Comment by mattifestation** [comment] 2022-03-02 17:25
PowerShell and WDAC on Server 2016 were more broken than I had anticipated! Thanks for reporting this, @mfgjwaterman. I committed the fixes that should get you proper support on Server 2016. Can you please test it out and close this issue out if it works for you? Thanks for your patience!

**Comment by mfgjwaterman** [comment] 2022-03-02 18:35
Hi Matt, did a quick test on the functionality that I need for 2016 (Get-WDACCodeIntegrityEvent) and that seems to work now. Thanks for the very fast reply and fix. While I'm at it, would you like me to do some tests on 2016? 

PS: On a completely different subject. The DenyAllAudit example policy mentioned in the YT videos seems to totally brick server 2019 atm. I've already reported this to Microsoft but no response thus far. Perhaps you have some contacts that you can use for that? 

Thanks again and keep up the fantastic work!

**Comment by mattifestation** [comment] 2022-03-03 11:13
I'm glad those fixes work for you!

I'll try to repro on Server 2019 and if it bricks for me, I'll file a Feedback Hub issue so that it's tracked. You may also want to reach out to [Jeffrey Sutherland](https://github.com/jsuther1974) at Microsoft. He has always been a great PoC for me when I'm desperate.

I'll reach back out to you if I'm able to repro the Server 2019 issue. Sorry you're encountering that!

**Comment by mattifestation** [comment] 2022-03-03 16:20
I just repro'd the Server 2019 issue with DenyAllAudit.xml in my Hyper-V VM. I even added `Enabled:Boot Audit On Failure` to the policy and it still won't boot. I haven't tried to identify the root cause but I just wanted to pass that on. That's definitely frustrating.

**Comment by mfgjwaterman** [comment] 2022-03-03 16:34
I'm actually somewhat glad that you got the same result. At some point during troubleshooting I really thought I was doing something wrong. Will you reach out to Jeffrey or should I?

**Comment by mattifestation** [comment] 2022-03-03 17:10
I don't have a ton of cycles to reach out so it would be best for you to. Thanks!!!

**Closed as completed by mattifestation** 2022-03-03 17:10 UTC

**Comment by mfgjwaterman** [comment] 2022-03-04 08:55
I've send the e-mail to Jeffrey, hopefully he can respond to a former colleague :-). Thanks for the help Matt, I'll let you know if I get any info.

**Comment by mfgjwaterman** [comment] 2022-03-25 08:18
Hi Matt,

Just got word from Jeffrey, they confirmed the bug. He wrote the following:

We did confirm a perf bug on Server 2019 causing significant delay to boot when using a WDAC policy that does not have allow rules covering the files that load during boot. The workaround is to switch from Deny All to one that at least authorizes all of the Windows signed code that is loaded during boot. Since the bug only exists in Server 2019 or client version 1809, we are not planning a fix at this time.

There won't be a fix, which, given the scope and impact, I understand from a business point of view. I asked if at least a KB article could be written to explain the situation and the workaround. 

Hope this helps! Be safe, 
Michael

**Comment by mattifestation** [comment] 2022-03-25 10:39
Thank you so much for following up, Michael! That's a bummer if one wanted to [explicitly allow each individual driver at boot](https://posts.specterops.io/adventures-in-extremely-strict-device-guard-policy-configuration-part-1-device-drivers-fd1a281b35a8) by starting with the deny all policy but I imagine there aren't too many people in that situation. Is that what you were hoping to do? So odd that it only affects Server 2019. 🤷

**Comment by mfgjwaterman** [comment] 2022-03-25 10:52
I know, right. I don't think a lot of companies use wdac in that strict manner. TBH I never thought about it before I ran into your YT videos.... and that got me thinking about it in more detail and realize that it's about explicit control rather than implicit control. What I also realize from the feedback that perhaps the usage of WDAC is relatively small. Still think it's a great way to block all kinds of nasty, but an IT department needs lots of training on the job to get it under control.  

Now with Microsoft purely focusing on Cloud, not enough attention is given to these features.... unfortunately..... on the other hand, there's where people like you and me can step up :-)
